server:
  port: 8761
security:
  basic:
    enabled: true #开启认证
  user:
    name: user
    password: 123456
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # 当前服务不需要到Eureka Server上注册
    fetch-registry: false  # 不需要从eureka服务器获取注册信息
    serviceUrl:
      defaultZone: http://user:password@${eureka.instance.hostname}:${server.port}/eureka/
